vdsm-kube:
  build: ./$MAJOR_VERSION
  environment:
    - ENGINE_FQDN=ovirt-engine
    - CLUSTER_GATEWAY=10.32.0.2
  privileged: true
  ports:
    - 54321:54321
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:Z
    - /dev:/dev:Z
    - /boot:/boot:Z
  restart: always
